import PDFDocument from 'pdfkit';
import cloudinary from '../config/cloudinary.js';

export const generateAndUpload80GReceipt = async (donor, ngo) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    
    // THE FIX: Stream straight to Cloudinary, skipping the hard drive!
    const uploadStream = cloudinary.uploader.upload_stream(
      {
        resource_type: 'raw', 
        folder: 'hopeworks_receipts',
        public_id: `receipt_${Date.now()}.pdf` 
      },
      (error, result) => {
        if (error) {
          console.error("Cloudinary Upload Error:", error);
          return reject(error);
        }
        resolve(result.secure_url);
      }
    );

    // Connect the PDF generation directly to the Cloudinary upload
    doc.pipe(uploadStream);

    // --- DRAW THE COMPLIANT PDF CONTENT ---
    doc.fontSize(18).font('Helvetica-Bold').text('Donation Receipt for 80G Tax Exemption', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).font('Helvetica-Bold').text('Issuer Details (NGO):');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Organization: ${ngo.name}`);
    doc.text(`Address: ${ngo.address}`);
    doc.text(`Darpan ID: ${ngo.darpanId || 'Not Provided'}`);
    doc.text(`NGO PAN: ${ngo.pan || 'Pending Verification'}`);
    doc.text(`80G Registration URN: ${ngo.urn || 'Pending Verification'}`);
    doc.text(`Email: ${ngo.email}`);
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Donor Details:');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Name: ${donor.name}`);
    doc.text(`Email: ${donor.email}`);
    if (donor.pan) {
      doc.text(`Donor PAN: ${donor.pan.toUpperCase()}`);
    } else {
      doc.text(`Donor PAN: Not Provided`);
    }
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Transaction Details:');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Date of Donation: ${new Date(donor.date || Date.now()).toLocaleDateString('en-IN')}`);
    doc.text(`Amount Received: INR ${donor.amount.toLocaleString('en-IN')}`);
    doc.text(`Payment ID: ${donor.paymentId}`);
    doc.moveDown(2);

    doc.fontSize(10).font('Helvetica-Bold').fillColor('#8B0000').text(`IMPORTANT DISCLAIMER:`, { align: 'center' });
    doc.font('Helvetica-Oblique').fillColor('black');
    doc.text(`This receipt is generated by HopeWorks acting solely as a technology service provider and is issued strictly on behalf of ${ngo.name}. HopeWorks is not a charitable institution and does not grant tax exemptions. Please verify the NGO's 80G status on the official Income Tax portal. The issuing NGO is solely responsible for filing Form 10BD for your tax claim.`, { align: 'center' });

    // Finalize the PDF (This automatically finishes the Cloudinary upload)
    doc.end();
  });
};