import PDFDocument from 'pdfkit';
import cloudinary from '../config/cloudinary.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generateAndUpload80GReceipt = async (donor, ngo) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    
    // 1. Create a temporary file on your local server
    const tempFileName = `temp_receipt_${Date.now()}.pdf`;
    const tempFilePath = path.join(__dirname, `../${tempFileName}`);
    const writeStream = fs.createWriteStream(tempFilePath);
    
    doc.pipe(writeStream);

    // --- 2. DRAW THE COMPLIANT PDF CONTENT ---
    
    // Updated Title: It is a Receipt, not a Certificate
    doc.fontSize(18).font('Helvetica-Bold').text('Donation Receipt for 80G Tax Exemption', { align: 'center' });
    doc.moveDown(2);

    // NGO Details (The Issuer)
    doc.fontSize(14).font('Helvetica-Bold').text('Issuer Details (NGO):');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Organization: ${ngo.name}`);
    doc.text(`Address: ${ngo.address}`);
    doc.text(`Darpan ID: ${ngo.darpanId || 'Not Provided'}`);
    // New Compliance Fields
    doc.text(`NGO PAN: ${ngo.pan || 'Pending Verification'}`);
    doc.text(`80G Registration URN: ${ngo.urn || 'Pending Verification'}`);
    doc.text(`Email: ${ngo.email}`);
    doc.moveDown();

    // Donor Details
    doc.fontSize(14).font('Helvetica-Bold').text('Donor Details:');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Name: ${donor.name}`);
    doc.text(`Email: ${donor.email}`);
    // Donor PAN (Mandatory for large donations/80G claims)
    if (donor.pan) {
      doc.text(`Donor PAN: ${donor.pan.toUpperCase()}`);
    } else {
      doc.text(`Donor PAN: Not Provided`);
    }
    doc.moveDown();

    // Transaction Details
    doc.fontSize(14).font('Helvetica-Bold').text('Transaction Details:');
    doc.fontSize(12).font('Helvetica');
    doc.text(`Date of Donation: ${new Date(donor.date).toLocaleDateString('en-IN')}`);
    doc.text(`Amount Received: INR ${donor.amount.toLocaleString('en-IN')}`);
    doc.text(`Payment ID: ${donor.paymentId}`);
    doc.moveDown(2);

    // --- THE VITAL LEGAL INDEMNITY DISCLAIMER ---
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#8B0000').text(`IMPORTANT DISCLAIMER:`, { align: 'center' });
    doc.font('Helvetica-Oblique').fillColor('black');
    doc.text(`This receipt is generated by HopeWorks acting solely as a technology service provider and is issued strictly on behalf of ${ngo.name}. HopeWorks is not a charitable institution and does not grant tax exemptions. Please verify the NGO's 80G status on the official Income Tax portal. The issuing NGO is solely responsible for filing Form 10BD for your tax claim.`, { align: 'center' });

    // 3. Finalize the PDF
    doc.end();

    // 4. Safely upload raw document to Cloudinary
    writeStream.on('finish', async () => {
      try {
        const result = await cloudinary.uploader.upload(tempFilePath, {
          resource_type: 'raw', 
          folder: 'hopeworks_receipts',
          public_id: `receipt_${Date.now()}.pdf` 
        });

        fs.unlinkSync(tempFilePath); // Clean up temp file
        resolve(result.secure_url);
      } catch (error) {
        console.error("Cloudinary Upload Error:", error);
        if (fs.existsSync(tempFilePath)) fs.unlinkSync(tempFilePath);
        reject(error);
      }
    });

    writeStream.on('error', (err) => {
       console.error("File write error:", err);
       reject(err);
    });
  });
};